---
- name: Check if omeka S directories already exists
  ansible.builtin.stat:
    path: "{{ omekaS_content_dest }}"
  register: omekaS_installed

- name: Create a configuration backup directory
  ansible.builtin.file:
    path: "{{ omekaS_backup_directory }}"
    state: directory

- name: Backup your configurations before update (Update only)
  ansible.builtin.copy:
    src: "{{ omekaS_content_dest }}/{{ item }}"
    dest: "{{ omekaS_backup_directory }}/{{ item }}"
    mode: '0640'
    force: true
  with_items:
    - "config"
    - "modules"
    - "themes"
    - "files"
  when: omekaS_installed.stat.exists and omekaS_update

- name: Download and extract Omeka S
  ansible.builtin.unarchive:
    src: "{{ omekaS_download_url }}"
    remote_src: true
    dest: "{{ omekaS_unarchive_dir }}"
    owner: "{{ omekaS_web_owner }}"
    group: "{{ omekaS_web_group }}"
    validate_certs: false
  when: not omekaS_installed.stat.exists or omekaS_update

- name: Set permisions to files directory
  ansible.builtin.file:
    path: "{{ omekaS_content_dest }}/files"
    owner: "{{ omekaS_web_owner }}"
    group: "{{ omekaS_web_group }}"
    mode: "0755"
  when: not omekaS_installed.stat.exists or omekaS_update

- name: Restore your configurations files (Update Only)
  ansible.builtin.copy:
    src: "{{ omekaS_content_dest }}/{{ item }}"
    dest: "{{ omekaS_backup_directory }}/{{ item }}"
    owner: "{{ omekaS_web_owner }}"
    group: "{{ omekaS_web_group }}"
    force: true
  with_items:
    - "config/local.config.php"
    - "modules"
    - "themes"
    - "files"
  when: omekaS_installed.stat.exists and omekaS_update

- name: Copy database.ini
  ansible.builtin.template:
    src: database.ini.j2
    owner: "{{ omekaS_web_owner }}"
    group: "{{ omekaS_web_group }}"
    dest: "{{ omekaS_content_dest }}/config/database.ini"
    mode: "0644"
  notify: Change Web directory owner
